//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mko.RPN.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mko.RPN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die begin größer als end ähnelt.
        /// </summary>
        internal static string begin_greater_then_end {
            get {
                return ResourceManager.GetString("begin_greater_then_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter {0:D} befindet sich vor dem mit begin ... end definierten Subset von Tokens ähnelt.
        /// </summary>
        internal static string begin_starts_later_then_param_i_of_function {
            get {
                return ResourceManager.GetString("begin_starts_later_then_param_i_of_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die boolscher Wert erwartet. Tatsächlich [0:s}. BoolToken oder die Zeichenketten &apos;true&apos; und &apos;false&apos; sind zulässig ähnelt.
        /// </summary>
        internal static string boolean_expected {
            get {
                return ResourceManager.GetString("boolean_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In dem String wurde ein boolsches Literal wie true oder false erwartet ähnelt.
        /// </summary>
        internal static string boolean_literal_expected {
            get {
                return ResourceManager.GetString("boolean_literal_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Variadische Parameterliste ist nicht mit Lend abgeschlossen worden ähnelt.
        /// </summary>
        internal static string ErrEval_VariadicParameterlistNotTerminiated {
            get {
                return ResourceManager.GetString("ErrEval_VariadicParameterlistNotTerminiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Anzahl der Parameter für {0:s} ist ungültig. ähnelt.
        /// </summary>
        internal static string EvalErr_InvalidParameterCount {
            get {
                return ResourceManager.GetString("EvalErr_InvalidParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Funktionsname ist null oder leer ähnelt.
        /// </summary>
        internal static string Functionname_null_or_empty {
            get {
                return ResourceManager.GetString("Functionname_null_or_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Funktions- Subtree wurde erwartet ähnelt.
        /// </summary>
        internal static string FunctionSubtreeExpected {
            get {
                return ResourceManager.GetString("FunctionSubtreeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Funktionstoken erwartet ähnelt.
        /// </summary>
        internal static string functiontoken_expected {
            get {
                return ResourceManager.GetString("functiontoken_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index lag außerhalb des Bereiches von Tokens, oder mit Index referenziertes Token ist keine Funktion ähnelt.
        /// </summary>
        internal static string GetFunction_index_out_of_range {
            get {
                return ResourceManager.GetString("GetFunction_index_out_of_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der in Token aufzulösende Datenstrom/String wurde noch nicht definiert ähnelt.
        /// </summary>
        internal static string missing_tokenizer_input_stream {
            get {
                return ResourceManager.GetString("missing_tokenizer_input_stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Tokens verweisen auf null ähnelt.
        /// </summary>
        internal static string Null_Ref_Tokens {
            get {
                return ResourceManager.GetString("Null_Ref_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nummerischer Wert erwarter. Stattdessen erhalten: {0:s} ähnelt.
        /// </summary>
        internal static string nummeric_expected {
            get {
                return ResourceManager.GetString("nummeric_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der {0:D}. Parameter existiert nicht. Es kann kein Parameter Subtree bestimmt werden ähnelt.
        /// </summary>
        internal static string ParameterSubtreeDontExists {
            get {
                return ResourceManager.GetString("ParameterSubtreeDontExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Index der Funktion, dessen Parameterindex bestimmt werden soll, war außerhalb des gültigen Bereiches ähnelt.
        /// </summary>
        internal static string ParserHelpler_IndexOfFunctionParameter_Function_Index_out_of_Range {
            get {
                return ResourceManager.GetString("ParserHelpler_IndexOfFunctionParameter_Function_Index_out_of_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Beginn des Suchbereiches liegt innerhalb der Parameterliste einer Funktion ähnelt.
        /// </summary>
        internal static string range_of_search_starts_inside_parameterlist {
            get {
                return ResourceManager.GetString("range_of_search_starts_inside_parameterlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Tokenisieren ist ein Fehler aufgetreten. Siehe innere Ausnahme. ähnelt.
        /// </summary>
        internal static string tokenizing_failed {
            get {
                return ResourceManager.GetString("tokenizing_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einem durch Delimiter begrenzten String fehlt der abschließende Delimiter.  ähnelt.
        /// </summary>
        internal static string tokenizing_failed_final_string_delimiter_missing {
            get {
                return ResourceManager.GetString("tokenizing_failed_final_string_delimiter_missing", resourceCulture);
            }
        }
    }
}
